### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by azhe403** [yesolutions/mirror-action#24]
I will sync github repo1 to github repo 2.
There already set some property with Secrets using username, password and repo url.
But where wrong until they say not found?

![image](https://user-images.githubusercontent.com/17938038/162640543-0526c8e2-612c-4724-b9d4-132cd642d6fa.png)
![image](https://user-images.githubusercontent.com/17938038/162640552-79121e8c-7fee-4203-8e12-0b850dfde22a.png)

**Comment by spyoungtech** [comment]
Hard to say what the problem might be here. I would double check that your remote value is correct. It's hidden in the logs because you used a secret to define it, so I can't say one way or the other if the value is correct.

As a possible tip: if you are using GitHub, I don't think you can use password authentication, maybe unless you're using a token because [password authentication was removed in August of 2021](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/).

**Comment by Neirie** [comment]
How can I change the remote to the good repository as I deleted the one (which was a test) ? 
remote: Repository not found.
fatal: repository 'https://github.com/Neirie/hellotest.git/' not found > he can't find it because it is deleted, how can i reinitiate the remote to the good repository please ? (i am new here) :)

**Comment by spyoungtech** [comment]
In your workflow YAML file, change the `REMOTE:` parameter to be the repository you want to use. If you're using a secret for this value, go into the repository settings -> secrets -> actions and set a new value.

**Comment by spyoungtech** [comment]
If you still need help, feel free to reopen this.
